version: "3.8"
services:
    Eye_disease:
        build: 
          dockerfile: ./docker/Dockerfile.server
          context: ./
        image: ed-base/py3:latest
        ports:
          - "6666:6666"
          - "8888:8888"
          - "5000:5000"
        volumes:
          - ./:/usr/src/app
          - /mnt/data:/data
          - /mnt/exps:/exps
        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: 1
                  capabilities: [gpu]
        environment:
          - PYTHONPATH=/usr/src/app
        working_dir: /usr/src/app
        tty: true 
        # env_file:
        #   - ./.env.dev
        # mem_limit: 2048M
        
        # entrypoint: ["bash" , './entrypoint.sh']
        # restart: unless-stopped