FROM ubuntu:latest

MAINTAINER Asiyeh Bahaloo

## setting timezone
ENV TZ="America/New_York"
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

## installing Python 3.8
RUN apt-get update && \
	apt-get install -y software-properties-common wget curl htop build-essential && \
	#add-apt-repository ppa:deadsnakes/ppa && \
	#apt-get update && \
	apt-get install -y python3.8 python3.8-dev python3-pip && \
	ln -s /usr/bin/python3.8 /usr/bin/python && \
	curl https://bootstrap.pypa.io/get-pip.py | python && \
	pip install --upgrade pip && \
	apt-get purge -y --auto-remove build-essential python3.8-dev && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/*
## Done with python installation 

## installing usefull tools and requirements for open-cv
RUN apt-get update && \
    apt-get install -y make htop wget && \
    apt-get install -y ffmpeg libsm6 libxext6 && \ 
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# set work directory
WORKDIR /usr/src/app

# install dependencies
COPY ./requirements.dev.txt .
RUN pip install --no-cache-dir -r requirements.dev.txt
CMD ["bash", "-D"]